version: "3.9"
# NOTE: tested on Windows with Docker Desktop (Docker Engine v20+ and docker-compose v1.29.2, build 5becea4c)
# 1.) Build docker images
# docker-compose build
# 2. ) Finally run the containers
# first the server is built and run, then client is built and run automatically
# docker-compose up
# docker-compose down
# review log folder in server_container directory after the containers exit
#

services:
    clangcon:
        build: .
        volumes:
            - './work:/mnt'
        working_dir: /mnt
        container_name: clangcon
        image: clangt/unit:1.1