if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
	option(CLANG_CODE_COVERAGE "enable coverage" OFF)
	if(CLANG_CODE_COVERAGE)
		message(STATUS "Coverage Enabled")
		set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -fprofile-instr-generate -fcoverage-mapping")
		set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fprofile-instr-generate -fcoverage-mapping")
		set(CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_EXE_LINKER_FLAGS_DEBUG} -fprofile-instr-generate -fcoverage-mapping")		
	endif()
endif()